name: CI Workflow

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dotnet/setup-dotnet
      - uses: ./.github/actions/dotnet/test-dotnet